// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuBsBS_xtqPCTqSTJw-25_z8mdq3Yw_pw',
    appId: '1:1068174629658:web:359f824b162f41c2fbeaa3',
    messagingSenderId: '1068174629658',
    projectId: 'smarttalk-f6959',
    authDomain: 'smarttalk-f6959.firebaseapp.com',
    storageBucket: 'smarttalk-f6959.appspot.com',
    measurementId: 'G-EBCV2Z7JWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClF0A5LqMxr50enmrpfiFOkAB8lVfzaAM',
    appId: '1:1068174629658:android:12ab204a79443824fbeaa3',
    messagingSenderId: '1068174629658',
    projectId: 'smarttalk-f6959',
    storageBucket: 'smarttalk-f6959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0N_E8JFRDqe7qRdvgac-A3dXYdFt423E',
    appId: '1:1068174629658:ios:59c39263745c2117fbeaa3',
    messagingSenderId: '1068174629658',
    projectId: 'smarttalk-f6959',
    storageBucket: 'smarttalk-f6959.appspot.com',
    iosClientId: '1068174629658-n6kjs796fsookdql7eklofqk0lej1o6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarttalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0N_E8JFRDqe7qRdvgac-A3dXYdFt423E',
    appId: '1:1068174629658:ios:59c39263745c2117fbeaa3',
    messagingSenderId: '1068174629658',
    projectId: 'smarttalk-f6959',
    storageBucket: 'smarttalk-f6959.appspot.com',
    iosClientId: '1068174629658-n6kjs796fsookdql7eklofqk0lej1o6e.apps.googleusercontent.com',
    iosBundleId: 'com.example.smarttalk',
  );
}
